import { MD3LightTheme, type MD3Theme } from "react-native-paper";

export const palette = {
  primary: "#A83524",
  onPrimary: "#FFFFFF",
  primaryContainer: "#F7E3DE",
  onPrimaryContainer: "#7A2414",
  secondary: "#FAD051",
  onSecondary: "#431407",
  secondaryContainer: "#FDF3D5",
  onSecondaryContainer: "#594500",
  tertiary: "#0F766E",
  onTertiary: "#FFFFFF",
  background: "#FAF9F6",
  onBackground: "#1F2937",
  surface: "#FFFFFF",
  onSurface: "#1F2937",
  surfaceVariant: "#F9FAFB",
  onSurfaceVariant: "#6B7280",
  surfaceDisabled: "#F3F4F6",
  outline: "#D1D5DB",
  outlineVariant: "#E5E7EB",
  error: "#DC2626",
  onError: "#FFFFFF",
  errorContainer: "#FEE2E2",
  onErrorContainer: "#7F1D1D",
  success: "#16A34A",
  onSuccess: "#FFFFFF",
  successContainer: "#DCFCE7",
  onSuccessContainer: "#14532D",
  warning: "#D97706",
  onWarning: "#FFFFFF",
  warningContainer: "#FEF3C7",
  onWarningContainer: "#78350F",
  info: "#2563EB",
  onInfo: "#FFFFFF",
  infoContainer: "#DBEAFE",
  onInfoContainer: "#1E3A8A",
  danger: "#DC2626",
  dangerContainer: "#FEE2E2",
  onDangerContainer: "#7F1D1D",
  gold: "#FAD051",
  backgroundGold: "#FBF6EA",
  disabled: "#A8A29E",
  black: "#000000",
  white: "#FFFFFF",
};

export const theme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 12,
  colors: {
    ...MD3LightTheme.colors,
    primary: palette.primary,
    onPrimary: palette.onPrimary,
    primaryContainer: palette.primaryContainer,
    onPrimaryContainer: palette.onPrimaryContainer,
    secondary: palette.secondary,
    onSecondary: palette.onSecondary,
    secondaryContainer: palette.secondaryContainer,
    onSecondaryContainer: palette.onSecondaryContainer,
    tertiary: palette.tertiary,
    onTertiary: palette.onTertiary,
    background: palette.background,
    onBackground: palette.onBackground,
    surface: palette.surface,
    onSurface: palette.onSurface,
    surfaceVariant: palette.surfaceVariant,
    onSurfaceVariant: palette.onSurfaceVariant,
    surfaceDisabled: palette.surfaceDisabled,
    outline: palette.outline,
    outlineVariant: palette.outlineVariant,
    error: palette.error,
    onError: palette.onError,
    errorContainer: palette.errorContainer,
    onErrorContainer: palette.onErrorContainer,
  },
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
} as const;

export const radius = {
  sm: 8,
  md: 12,
  lg: 16,
  pill: 999,
} as const;